#!/bin/sh
# Copyright (C) 2026 David Nichols
# SPDX-License-Identifier: MIT
set -eu
unset QORE_MODULE_DIR QORE_MODULE_DIR_ONLY QORE_INCLUDE_DIR LD_LIBRARY_PATH LD_PRELOAD
unset ORACLE_HOME ORACLE_INSTANT_CLIENT ORACLE_INCLUDES TNS_ADMIN
cp test/oracle-offline.qtest "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
exec /usr/bin/qore oracle-offline.qtest -v
